### ISSUE TITLE
Problem in the `tanhx` function in the neural networks section

### ISSUE THREAD

**Issue by pcotret** [QDucasse/msc_research_report#3]
I may be wrong but it seems there's an error in the 2.3.3.1 section "Neural Networks"

<img src="http://latex2png.com/pngs/e4b1642152dc12bc78f70d6b6b787a68.png" data-canonical-src="http://latex2png.com/pngs/e4b1642152dc12bc78f70d6b6b787a68.png" width="300"/>

Just missing the final `-1` :wink:

**Comment by QDucasse** [comment]
That's true, corrected!
